server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
            tag: attrs.tag
      - regex:
          source: tag
          expression: '(?P<container_name>(?:[^|]*))'
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  - job_name: enhanced-cognee
    static_configs:
      - targets:
          - localhost
        labels:
          job: enhanced-cognee
          __path__: /var/log/enhanced-cognee/*.log
