"""
auto_port.py
============
Reads the last diff report produced by upstream_diff.py and generates:
  - Stub MCP tool functions for each new upstream task
  - A TODO checklist (Markdown) listing all manual porting steps

Usage
-----
    python scripts/auto_port.py [--report PATH] [--out-stubs PATH] [--out-todo PATH]

Flags
-----
--report PATH    Path to upstream diff JSON report
                 (default: .upstream-sync/last_diff_report.json)
--out-stubs PATH Output Python file for generated stubs
                 (default: .upstream-sync/generated_stubs.py)
--out-todo PATH  Output Markdown TODO checklist
                 (default: .upstream-sync/PORTING_TODO.md)
--dry-run        Print generated content to stdout only, do not write files.

Exit codes
----------
0  Success
1  No diff report found or fatal error
2  Diff report exists but no new items detected (no work to do)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SYNC_DIR = Path(__file__).parent.parent / ".upstream-sync"
DEFAULT_REPORT = SYNC_DIR / "last_diff_report.json"
DEFAULT_STUBS = SYNC_DIR / "generated_stubs.py"
DEFAULT_TODO = SYNC_DIR / "PORTING_TODO.md"
MCP_SERVER = Path(__file__).parent.parent / "bin" / "enhanced_cognee_mcp_server.py"


# ---------------------------------------------------------------------------
# Stub generator
# ---------------------------------------------------------------------------

def _task_path_to_tool_name(task_path: str) -> str:
    """
    Convert 'cognee/tasks/foo_bar_task.py' -> 'foo_bar'
    Strips leading 'cognee/tasks/', strips '_task.py' or '.py' suffix.
    """
    name = Path(task_path).stem  # e.g. 'foo_bar_task'
    name = re.sub(r"_task$", "", name)  # 'foo_bar'
    return name


def _snake_to_title(name: str) -> str:
    return " ".join(w.capitalize() for w in name.split("_"))


def generate_task_stub(task_path: str) -> str:
    """Generate a stub MCP tool function for a new upstream task file."""
    tool_name = _task_path_to_tool_name(task_path)
    title = _snake_to_title(tool_name)
    stub = textwrap.dedent(f"""\
        @mcp.tool()
        async def {tool_name}(
            data: str,
            dataset_name: str = "main",
        ) -> str:
            \"\"\"[STUB] {title}.

            This stub was auto-generated by scripts/auto_port.py from upstream task:
                {task_path}

            Replace this body with a real implementation that calls the task.
            \"\"\"
            # TODO: implement - see upstream/{task_path}
            return (
                "WARN {tool_name} is not yet implemented. "
                "Port {task_path} from upstream to complete this tool."
            )
    """)
    return stub


def generate_search_type_note(new_types: list[str]) -> str:
    """Generate a comment block noting new SearchType values to add."""
    if not new_types:
        return ""
    lines = ["# TODO: Add the following SearchType values to _VALID_SEARCH_TYPES"]
    for t in new_types:
        lines.append(f'#     "{t}",')
    return "\n".join(lines) + "\n"


def generate_api_route_note(new_routes: list[str]) -> str:
    """Generate stubs for new upstream API routes."""
    if not new_routes:
        return ""
    lines = ["# TODO: Implement MCP tools for the following new upstream API routes:"]
    for route in new_routes:
        lines.append(f"#   {route}")
    return "\n".join(lines) + "\n"


def generate_stubs_file(report: dict) -> str:
    """Return the full content of the generated_stubs.py file."""
    delta = report.get("delta", {})
    new_tasks: list[str] = delta.get("new_tasks", [])
    new_search_types: list[str] = delta.get("new_search_types", [])
    new_api_routes: list[str] = delta.get("new_api_routes", [])
    upstream_latest: str = report.get("upstream_latest", "unknown")
    generated_at: str = report.get("generated_at", datetime.now(timezone.utc).isoformat())

    header = textwrap.dedent(f"""\
        \"\"\"
        Generated MCP tool stubs
        ========================
        Auto-generated by scripts/auto_port.py from diff report.
        Upstream version : {upstream_latest}
        Generated at     : {generated_at}

        HOW TO USE
        ----------
        1. Copy each stub into bin/enhanced_cognee_mcp_server.py after the
           last @mcp.tool() block.
        2. Replace the stub body with a real implementation.
        3. Run the test suite: python -m pytest tests/unit/ -q
        4. Update .upstream-sync/last_seen_release.txt to {upstream_latest}
        \"\"\"

        # ruff: noqa
        # mypy: ignore-errors
        from typing import Optional

        # The 'mcp' object is defined in the real MCP server file.
        # This stub file is for reference only - paste functions into the server.
        # mcp = FastMCP(...)

    """)

    parts = [header]

    if new_search_types:
        parts.append(generate_search_type_note(new_search_types))
        parts.append("\n")

    if new_api_routes:
        parts.append(generate_api_route_note(new_api_routes))
        parts.append("\n")

    if new_tasks:
        parts.append("# ---------------------------------------------------------------------------\n")
        parts.append("# Auto-generated stubs for new upstream tasks\n")
        parts.append("# ---------------------------------------------------------------------------\n\n")
        for task_path in new_tasks:
            parts.append(generate_task_stub(task_path))
            parts.append("\n\n")

    if not new_tasks and not new_search_types and not new_api_routes:
        parts.append("# No new MCP-relevant items detected in this upstream release.\n")

    return "".join(parts)


# ---------------------------------------------------------------------------
# TODO checklist generator
# ---------------------------------------------------------------------------

def generate_todo_markdown(report: dict) -> str:
    delta = report.get("delta", {})
    new_tasks: list[str] = delta.get("new_tasks", [])
    new_search_types: list[str] = delta.get("new_search_types", [])
    new_api_routes: list[str] = delta.get("new_api_routes", [])
    changed_files: list[str] = delta.get("changed_files", [])
    upstream_latest: str = report.get("upstream_latest", "unknown")
    local_baseline: str = report.get("local_baseline", "unknown")
    generated_at: str = report.get("generated_at", "")

    lines = [
        f"# Porting TODO: {local_baseline} -> {upstream_latest}",
        "",
        f"Generated: {generated_at}",
        "",
        "## Summary",
        "",
        f"- New upstream tasks   : {len(new_tasks)}",
        f"- New API routes       : {len(new_api_routes)}",
        f"- New SearchType values: {len(new_search_types)}",
        f"- Changed cognee/ files: {len(changed_files)}",
        "",
    ]

    if new_tasks:
        lines += [
            "## New Upstream Tasks (generate MCP tools)",
            "",
            "Stubs are in `.upstream-sync/generated_stubs.py`. For each:",
            "",
        ]
        for t in new_tasks:
            lines.append(f"- [ ] Port `{t}` -> implement MCP tool `{_task_path_to_tool_name(t)}`")
        lines.append("")

    if new_search_types:
        lines += [
            "## New SearchType Values",
            "",
            "Add to `_VALID_SEARCH_TYPES` set in `bin/enhanced_cognee_mcp_server.py`:",
            "",
        ]
        for st in new_search_types:
            lines.append(f'- [ ] Add `"{st}"` to `_VALID_SEARCH_TYPES`')
        lines.append("")

    if new_api_routes:
        lines += [
            "## New API Routes",
            "",
            "Consider adding MCP tools for these new endpoints:",
            "",
        ]
        for route in new_api_routes:
            lines.append(f"- [ ] Implement MCP tool for `{route}`")
        lines.append("")

    if changed_files:
        lines += [
            "## Changed cognee/ Files (review for porting)",
            "",
            "These files changed between releases. Review for logic updates to port:",
            "",
        ]
        for f in changed_files[:30]:
            lines.append(f"- [ ] Review `{f}`")
        if len(changed_files) > 30:
            lines.append(f"- ... and {len(changed_files) - 30} more (see full report JSON)")
        lines.append("")

    lines += [
        "## Checklist: Final Steps",
        "",
        "- [ ] Copy stubs from `.upstream-sync/generated_stubs.py` into `bin/enhanced_cognee_mcp_server.py`",
        "- [ ] Implement each stub body",
        "- [ ] Verify `@mcp.tool()` decorator count in test: `test_tool_count_is_70` (update expected count)",
        "- [ ] Run `python -m pytest tests/unit/ -q`",
        f"- [ ] Update `.upstream-sync/last_seen_release.txt` to `{upstream_latest}`",
        f"- [ ] Update `upstream_last_synced` in `.upstream-sync/sync-metadata.json` to `{upstream_latest}`",
        "- [ ] Commit with message: `chore: port upstream {upstream_latest} changes`",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Duplicate check
# ---------------------------------------------------------------------------

def read_existing_tool_names() -> set[str]:
    """Return the set of existing async def names in the MCP server."""
    if not MCP_SERVER.exists():
        return set()
    content = MCP_SERVER.read_text(encoding="utf-8", errors="replace")
    return set(re.findall(r"^async def (\w+)\(", content, re.MULTILINE))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate MCP tool stubs and TODO list from upstream diff report."
    )
    p.add_argument(
        "--report",
        default=str(DEFAULT_REPORT),
        help=f"Path to upstream diff JSON (default: {DEFAULT_REPORT})",
    )
    p.add_argument(
        "--out-stubs",
        default=str(DEFAULT_STUBS),
        help=f"Output Python stubs file (default: {DEFAULT_STUBS})",
    )
    p.add_argument(
        "--out-todo",
        default=str(DEFAULT_TODO),
        help=f"Output Markdown TODO file (default: {DEFAULT_TODO})",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output to stdout, do not write files.",
    )
    return p.parse_args()


def main() -> int:
    args = _parse_args()
    report_path = Path(args.report)

    if not report_path.exists():
        print(
            f"ERR Diff report not found at {report_path}. "
            "Run scripts/upstream_diff.py first."
        )
        return 1

    report = json.loads(report_path.read_text(encoding="utf-8"))
    delta = report.get("delta", {})
    new_tasks = delta.get("new_tasks", [])
    new_search_types = delta.get("new_search_types", [])
    new_api_routes = delta.get("new_api_routes", [])

    if not new_tasks and not new_search_types and not new_api_routes:
        print("OK No new MCP-relevant items in diff report. Nothing to port.")
        return 2

    # Filter out tasks whose tool names already exist in MCP server
    existing = read_existing_tool_names()
    original_count = len(new_tasks)
    new_tasks = [
        t for t in new_tasks
        if _task_path_to_tool_name(t) not in existing
    ]
    if original_count != len(new_tasks):
        skipped = original_count - len(new_tasks)
        print(f"INFO Skipped {skipped} task(s) already implemented in MCP server.")
        report["delta"]["new_tasks"] = new_tasks

    stubs_content = generate_stubs_file(report)
    todo_content = generate_todo_markdown(report)

    if args.dry_run:
        print("=" * 60)
        print("-- STUBS (generated_stubs.py) --")
        print(stubs_content)
        print("=" * 60)
        print("-- TODO (PORTING_TODO.md) --")
        print(todo_content)
        return 0

    # Write files
    stubs_path = Path(args.out_stubs)
    todo_path = Path(args.out_todo)
    stubs_path.parent.mkdir(parents=True, exist_ok=True)
    todo_path.parent.mkdir(parents=True, exist_ok=True)

    stubs_path.write_text(stubs_content, encoding="utf-8")
    todo_path.write_text(todo_content, encoding="utf-8")

    print(f"OK Stubs written  : {stubs_path}")
    print(f"OK TODO written   : {todo_path}")
    print(f"INFO New tasks     : {len(new_tasks)}")
    print(f"INFO New types     : {len(new_search_types)}")
    print(f"INFO New routes    : {len(new_api_routes)}")
    print("")
    print("Next steps:")
    print("  1. Review .upstream-sync/PORTING_TODO.md")
    print("  2. Copy stubs from .upstream-sync/generated_stubs.py into the MCP server")
    print("  3. Implement each stub, run tests, commit")

    return 0


if __name__ == "__main__":
    sys.exit(main())
